### ISSUE TITLE
Export module not working

### ISSUE THREAD

**Issue by samualon** [samualon/Photoshop-automation#4]
main.py` needs to be ran as administrator for it to be able to dispatch the options dialogue. 
The code returns this error after a while:
```
Traceback (most recent call last):
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Samuel\OneDrive - KU Leuven\Persoonlijk\Coding Projects\Python\Photoshop-automation\main.py", line 5, in <module>
    psApp = win32com.client.Dispatch("Photoshop.Application")
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\__init__.py", line 117, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python38\lib\site-packages\win32com\client\dynamic.py", line 88, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(
pywintypes.com_error: (-2146959355, 'Server execution failed', None, None)
```

**Comment by samualon** [comment]
Rewrote some of the refs which made it work succesfully.
