### ISSUE TITLE
win32com.client.Dispatch can't find Photoshop application

### ISSUE THREAD

**Issue by samualon** [samualon/Photoshop-automation#7]
The win32com.client.Dispatch doensn't detect the newest version of Photoshop in the COM list. Can't check in combrowse.py as this seems to crash. This is the returned error after entering ```autophoto.py "C:\Users\Samuel\OneDrive - KU Leuven\Persoonlijk\Coding Projects\Python\Photoshop-automation" custom "test yes":```
```λ autophoto.py "C:\Users\Samuel\OneDrive - KU Leuven\Persoonlijk\Coding Projects\Python\Photoshop-automation" custom "test yes"
Traceback (most recent call last):
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Samuel\OneDrive - KU Leuven\Persoonlijk\Coding Projects\Python\Photoshop-automation\autophoto.py", line 39, in <module>
    psApp = win32com.client.Dispatch("Photoshop.Application")
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\__init__.py", line 117, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch, None, clsctx, pythoncom.IID_IDispatch
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)```

(Stackoverflow post: https://stackoverflow.com/questions/71395706/win32com-client-dispatchphotoshop-application-not-working-win32com-doesnt)

**Comment by samualon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Export bug](https://trello.com/c/UVZIHo4K/1-export-bug)

**Comment by paolo451** [comment]
Hi, did you find any solution?

**Comment by samualon** [comment]
> Hi, did you find any solution?

Since it's been a while I've been busy working on this project, I can't perfectly remember what we did to fix it. ATM it's working fine, so you can copy the code and normally it would have to work. My main two guesses to how we fixed it is 1: removing any old remnants of old Photoshop versions; 2: Make sure pywin32 is installed to be able to use win32com.client in your code.
